This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./2020_EFM_MPM_Eigensoftening.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 2020_EFM_MPM_Eigensoftening.acn....done (30 entries accepted, 0 rejected).
Sorting entries....done (167 comparisons).
Generating output file 2020_EFM_MPM_Eigensoftening.acr....done (22 lines written, 0 warnings).
Output written in 2020_EFM_MPM_Eigensoftening.acr.
Transcript written in 2020_EFM_MPM_Eigensoftening.alg.
